In [ ]:
!pip install numpy

In [ ]:
import numpy as np

In [ ]:
a = np.arange(12)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [ ]:
print(a[11])

11


In [ ]:
print(a[len(a)-1])

11


In [ ]:
print(a[-1])

11


In [ ]:
print(a[-2])

10


In [ ]:
print(a[10:])

print(a[-2:])


[10 11]
[10 11]


In [ ]:
a = np.arange(12)
print(a)
print(a[-4:])
print(np.sum(a[-4:]))

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 8  9 10 11]
38


In [ ]:
print(5*1)
print(5*True)
print(5*False)


5
5
0


In [ ]:
a = np.array([0,1,2,3,4,5])
# b = np.array([0,0,0,1,1,1])
b = np.array([False, False, False, True, True, True])

print(a*b)

[0 0 0 3 4 5]


In [ ]:
a = np.arange(12)

mask = a%2==0
print(a)
print(mask)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ True False  True False  True False  True False  True False  True False]


In [ ]:
a = np.arange(25).reshape((5,5))
mask = np.array([[1,1,1,1,1],
                 [1,0,0,0,1],
                 [1,0,0,0,1],
                 [1,0,0,0,1],
                 [1,1,1,1,1]])
print(a)
print(mask)
print(a*mask)
print(np.sum(a*mask))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]
[[ 0  1  2  3  4]
 [ 5  0  0  0  9]
 [10  0  0  0 14]
 [15  0  0  0 19]
 [20 21 22 23 24]]
192


In [ ]:
a = np.arange(25).reshape((5,5))
mask = np.ones_like(a)
mask[1:-1,1:-1] = 0


print(a)
print(mask)
print(a*mask)
print(np.sum(a*mask))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]
[[ 0  1  2  3  4]
 [ 5  0  0  0  9]
 [10  0  0  0 14]
 [15  0  0  0 19]
 [20 21 22 23 24]]
192


In [ ]:
a = np.arange(25).reshape((5,5))
mask = np.eye(5)

print(a)
print(mask)
print(a*mask)
print(np.sum(a*mask))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[ 0.  0.  0.  0.  0.]
 [ 0.  6.  0.  0.  0.]
 [ 0.  0. 12.  0.  0.]
 [ 0.  0.  0. 18.  0.]
 [ 0.  0.  0.  0. 24.]]
60.0


In [ ]:
a = [0,1,2,3,4]
print(a)
a.insert(3,99)
print(a)

[0, 1, 2, 3, 4]
[0, 1, 2, 99, 3, 4]


In [ ]:
a = np.arange(4)
print(a)
print(a.shape)

a = a.reshape((4,1))
print(a)
print(a.shape)

a = a.reshape((1,4))
print(a)
print(a.shape)

a = a.reshape((2,2))
print(a)
print(a.shape)

[0 1 2 3]
(4,)
[[0]
 [1]
 [2]
 [3]]
(4, 1)
[[0 1 2 3]]
(1, 4)
[[0 1]
 [2 3]]
(2, 2)


In [ ]:
a = np.arange(4)
a = np.expand_dims(a, axis=0)
print(a)
print(a.shape)

a = np.arange(4)
a = np.expand_dims(a, axis=1)
print(a)
print(a.shape)

a = np.arange(4)
a = np.expand_dims(a, axis=-1)
print(a)
print(a.shape)

[[0 1 2 3]]
(1, 4)
[[0]
 [1]
 [2]
 [3]]
(4, 1)
[[0]
 [1]
 [2]
 [3]]
(4, 1)


In [ ]:
a = np.arange(6).reshape((2,3))
print(a)
print(a.shape)

[[0 1 2]
 [3 4 5]]
(2, 3)


In [ ]:
a = np.arange(6).reshape((2,3))
a = np.expand_dims(a, axis=0)
print(a)
print(a.shape)

a = np.arange(6).reshape((2,3))
a = np.expand_dims(a, axis=1)
print(a)
print(a.shape)

a = np.arange(6).reshape((2,3))
a = np.expand_dims(a, axis=2)
print(a)
print(a.shape)


[[[0 1 2]
  [3 4 5]]]
(1, 2, 3)
[[[0 1 2]]

 [[3 4 5]]]
(2, 1, 3)
[[[0]
  [1]
  [2]]

 [[3]
  [4]
  [5]]]
(2, 3, 1)


In [ ]:
a = np.arange(12).reshape((1,3,4))
print(a)
print(a.shape)
a = np.squeeze(a)
print(a)
print(a.shape)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]]
(1, 3, 4)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)


In [ ]:
a = np.arange(12).reshape((1,3,1,4))
print(a)
print(a.shape)
a = np.squeeze(a)
print(a)
print(a.shape)

[[[[ 0  1  2  3]]

  [[ 4  5  6  7]]

  [[ 8  9 10 11]]]]
(1, 3, 1, 4)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)


In [ ]:
a = np.arange(12)

# a = a.reshape((3,4))
a = a.reshape((3,-1))
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
a = np.arange(12).reshape((3,4))
print(a)
print(a.T)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [ ]:
a = np.arange(12).reshape((1,3,1,4))
a = np.squeeze(a, axis=0)
print(a.shape)

(3, 1, 4)


In [ ]:
a = np.arange(15).reshape((5,3))
print(a)

print(np.sum(a, axis=0))

print(np.sum(a, axis=1))


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
[30 35 40]
[ 3 12 21 30 39]


In [ ]:
a = np.arange(15).reshape((5,3))
print(a)

print(np.mean(a, axis=0))

print(np.mean(a, axis=1))


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
[6. 7. 8.]
[ 1.  4.  7. 10. 13.]


In [ ]:
a = np.arange(60).reshape((3,4,5))
print(np.sum(a, axis=2).shape)
# (3,4)

print(np.sum(a, axis=0).shape)
# (4,5)

print(np.sum(a, axis=1).shape)
# (3,5)


(3, 4)
(4, 5)
(3, 5)


In [ ]:
a = np.array([ [170, 65],
               [165, 75],
               [171, 70],
               [155, 50],
               [165, 55] ])

print(np.mean(a, axis=0))
print(np.max(a, axis=0))
print(np.argmax(a, axis=0))

[165.2  63. ]
[171  75]
[2 1]


In [ ]:
a = np.array([ 1,3,5,2,4 ])
print(np.max(a))
print(np.argmax(a))

5
2


In [ ]:
a = np.arange(24).reshape((2,3,4))
print(np.sum(a, axis=(1,2)))

[ 66 210]


In [ ]:
a = np.random.rand(12).reshape((4,3))
print(a)
print(np.argmax(a, axis=1))

[[0.73028677 0.40252508 0.38249786]
 [0.29536428 0.14307121 0.41597248]
 [0.05062514 0.1683436  0.20693198]
 [0.64427131 0.10279808 0.25464796]]
[0 2 2 0]


In [ ]:
a = np.array( [ 3,7,5,1,8,6,4] )
print(np.sort(a))
print(np.argsort(a))

[1 3 4 5 6 7 8]
[3 0 6 2 5 1 4]


In [ ]:
a = np.arange(6).reshape((2,3))
b = np.arange(6,12).reshape((2,3))
print(a)
print(b)
print(np.vstack([a,b]))
print(np.hstack([a,b]))

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 0  1  2  6  7  8]
 [ 3  4  5  9 10 11]]


In [ ]:
a = np.arange(12).reshape((3,4))
np.savetxt("my_data.csv", a, delimiter=",")

In [ ]:
b = np.loadtxt("my_data.csv", delimiter=",")
print(b)

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]


In [ ]:
print(b.dtype)

float64


In [ ]:
print(b.astype(np.int))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
a = np.arange(6)
print(a)
print(a.astype(np.float))

[0 1 2 3 4 5]
[0. 1. 2. 3. 4. 5.]


In [ ]:
names = np.array(["tom", "jerry", "brute", "철수", "영희"])
print(names)
heights = np.array([170, 177, 165, 155, 175])
print(heights)
print(np.sort(heights))
print(np.argsort(heights))

height_ordered_index = np.array([3, 2, 0, 4, 1])
print(names[height_ordered_index])

['tom' 'jerry' 'brute' '철수' '영희']
[170 177 165 155 175]
[155 165 170 175 177]
[3 2 0 4 1]
['철수' 'brute' 'tom' '영희' 'jerry']


In [ ]:
aa = [ 0, 1, 2, 3, 4]

print(aa[3,4,5])

TypeError: ignored

In [ ]:
names = np.array(["tom", "jerry", "brute", "철수", "영희"])
heights = np.array([170, 177, 165, 155, 175])

print(names[np.argsort(heights)])

['철수' 'brute' 'tom' '영희' 'jerry']


In [ ]:
i = np.array([ 0, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2])
print(names[i])

['tom' '철수' '영희' 'jerry' 'brute' '철수' '영희' 'jerry' 'brute' '철수' '영희'
 'jerry' 'brute']


In [ ]:
category_indexes = np.array([ 0, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2])
e = np.eye(5)
one_hot_encoded = e[category_indexes]
predicted = np.argmax(one_hot_encoded, axis=1)
print(predicted)


[0 3 4 1 2 3 4 1 2 3 4 1 2]
